### ISSUE TITLE
tarihe gore siralama

### ISSUE THREAD

**Issue by mustafauysal** [codeui/chevent-chrome#10]
Etkinlik siralamasi yaparken, en yakin etkinlik en ustte olacak sekilde olursa daha guzel olur sanki.

<img width="373" alt="screen shot 2015-10-09 at 11 13 56" src="https://cloud.githubusercontent.com/assets/1421387/10412926/09ea4de6-6f9f-11e5-947f-eb501b9856ad.png">

**Comment by smtaydemir** [comment]
@mustafauysal Evet abi o şekilde daha mantıklı olur, bi sıralama ve countdown ekledim.

**Comment by mustafauysal** [comment]
:+1:

**Comment by previousdeveloper** [comment]
fixed orderBy:'event_date_ddmmyyyy'.
